# Timing constraints for both M2 link configurations.
#
# link_clk is generated by the RP2354A PIO, so its period is a firmware
# constant, not a board property. The value below started as the TARGET for the
# M2 sweep - 40 ns (25 MHz), lowered each time a hardware measurement came back
# clean - because the point where Efinity stops closing and the point where the
# board stops working are two different numbers, and M2 wanted both.
#
# M2 answered that: the board runs at 75 MHz, zero errors, 8.94 MB/s. So the
# sweep is over and this is now a statement of the operating point rather than a
# guess at it. It was left at 40 ns for the whole of M2, which meant the probes
# closed on 37.263 ns of slack against a 365 MHz Fmax and the report said
# nothing anyone read. A 40 ns constraint on a 13.333 ns clock is not
# conservative, it is unconstrained.
#
# gemm_top has its own gemm_top.sdc; this file covers the M2 probes only.
#
# clk_32m is the Y2 oscillator and is fixed.
#
# There is no path between the two domains - the heartbeat counter and the link
# shift register share nothing - so no cross-domain exception is needed. That is
# true here and NOT true of gemm_top, which crosses two diagnostic bits.

create_clock -period 13.333 -name link_clk [get_ports {link_clk}]
create_clock -period 31.250 -name clk_32m  [get_ports {clk_32m}]
