# /// script
# requires-python = ">=3.10"
# ///
"""Turn an Efinity bitstream into a C array for embedding in the firmware.

    uv run tools/hex2c.py rtl/build/link_narrow.hex build/bitstream.c
    uv run tools/hex2c.py rtl/build/probe_a.hex build/probe_a.c --symbol probe_a

Accepts Efinity ASCII .hex (whitespace-separated hex bytes) or a raw .bin. The
CRC is printed so the value the firmware ships can be matched against the value
host/load.py reports for the same file.

`--symbol` renames the emitted globals so more than one bitstream can be linked
into the same binary - which is what the diagnostic build does to compare a
known-good vendor image against ours without reflashing in between.
"""

import re
import sys
import zlib
from pathlib import Path


def load(path: Path) -> bytes:
    raw = path.read_bytes()
    if path.suffix.lower() != ".hex":
        return raw
    compact = re.sub(r"\s+", "", raw.decode("ascii"))
    if len(compact) % 2:
        raise SystemExit(f"{path}: odd number of hex digits")
    return bytes.fromhex(compact)


def main() -> int:
    argv = sys.argv[1:]
    symbol = "fpga_bitstream"
    if "--symbol" in argv:
        i = argv.index("--symbol")
        symbol = argv[i + 1]
        del argv[i : i + 2]
    if len(argv) != 2:
        raise SystemExit(__doc__)
    src, dst = Path(argv[0]), Path(argv[1])

    if not src.exists():
        # A missing bitstream is the normal state until Efinity has run, so emit
        # a valid but empty array rather than failing the build. The firmware
        # reports a zero length and refuses to run the sweep, which is a much
        # clearer failure than a CMake error three levels down.
        data, name = b"", f"MISSING: {src.name}"
        print(f"hex2c: {src} not found - embedding an empty placeholder")
    else:
        data = load(src)
        name = src.name
        print(f"hex2c: {src} -> {len(data)} bytes, crc32=0x{zlib.crc32(data):08X}")

    body = "\n".join(
        "    " + " ".join(f"0x{b:02X}," for b in data[i : i + 12])
        for i in range(0, len(data), 12)
    )

    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(
        "// Generated by tools/hex2c.py - do not edit.\n"
        "#include <stddef.h>\n#include <stdint.h>\n\n"
        f'const char *{symbol}_name = "{name}";\n'
        f"const size_t {symbol}_len = {len(data)};\n"
        f"const uint8_t {symbol}[] = {{\n" + body + "\n};\n"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
